controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rotation1
      - rotation2
      - gripper_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger1_joint
      - finger2_joint
      - finger3_joint
      - finger4_joint
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []