arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rotation1
    - rotation2
    - gripper_joint
  gains:
    rotation1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rotation2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger1_joint
    - finger2_joint
    - finger3_joint
    - finger4_joint
  gains:
    finger1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1